import type { GraphData } from "@finiq/graph-viewer";
import type {
  GovernanceTransitionCase,
  GovernanceTransitionEvent,
} from "./governanceTransitionModel";

export const DAEYANG_CROWDWORKS_EVENTS: GovernanceTransitionEvent[] = [
  {
    id: "sfc-precursor",
    date: "2016-09",
    categoryId: "acquisition",
    status: "analysis",
    path: "대표자 가지급금 → 태가 → 에스에프씨",
    scale: "70억",
    title: "소자본 인수 뒤 회사 자금조달이 붙은 선행 사례",
    summary: "자본금 4억원인 태가가 대표자 가지급금으로 에스에프씨 9.22%를 인수했고, 같은 날 에스에프씨는 전환사채와 유상증자 265억원을 결정했습니다.",
    evidence: "공시 분석상 인수 주체의 자체 자본보다 대표자 자금과 인수 대상 회사의 후속 자금조달 규모가 컸습니다.",
    sourceLabel: "DRCR 에스에프씨 인수 분석",
    sourceUrl: "https://www.drcr.co.kr/articles/388",
    graphNodeId: "history:sfc-takeover",
  },
  {
    id: "daeyang-holdings-control",
    date: "2020-04",
    categoryId: "control",
    status: "filing",
    path: "이옥순 96% → 대양홀딩스컴퍼니 → 대양금속",
    scale: "100억",
    title: "대양홀딩스컴퍼니가 대양금속 지배권 확보",
    summary: "이옥순이 96%를 보유한 대양홀딩스컴퍼니가 제3자배정 유상증자로 대양금속 최대주주가 된 연결입니다.",
    evidence: "KRX 공시의 투자자 기본정보에서 이옥순 96% 보유를 확인했고, 공시 분석은 대양금속 제3자배정 금액을 100억원으로 집계했습니다.",
    sourceLabel: "KRX 대양홀딩스컴퍼니 기본정보",
    sourceUrl: "https://kind.krx.co.kr/",
    graphNodeId: "organization:daeyang-holdings",
  },
  {
    id: "youngpoong-acquisition",
    date: "2022-11",
    categoryId: "acquisition",
    status: "analysis",
    path: "보유현금·CB·차입 → 대양금속 → 영풍제지",
    scale: "1,300억",
    title: "영풍제지 50.76% 인수, 원래 현금은 약 60억원",
    summary: "공시상 총 인수가는 약 1,300억원입니다. 공시 분석은 대양금속의 원래 현금을 약 60억원, 사채와 차입을 포함한 조달액을 약 1,240억원으로 봤습니다.",
    evidence: "인수금액과 지분율은 공시 확인값입니다. 60억원과 1,240억원은 여러 자금조달 공시를 합산한 분석값입니다.",
    sourceLabel: "DRCR 영풍제지 인수자금 분석",
    sourceUrl: "https://www.drcr.co.kr/articles/384",
    graphNodeId: "event:youngpoong-acquisition",
  },
  {
    id: "youngpoong-share-collateral",
    date: "2022-11",
    categoryId: "acquisition",
    status: "analysis",
    path: "대주단 → 대양금속 → 영풍제지 주식 담보",
    scale: "761억",
    title: "인수대상 주식이 인수금융 담보로 제공",
    summary: "인수자금 차입 861억원 가운데 약 761억원은 취득한 영풍제지 주식을 담보로 한 것으로 분석됐습니다.",
    evidence: "인수 대상의 주식을 담보로 조달한 차입이 전체 인수대금의 큰 부분을 차지하는 무자본 M&A 관찰 지점입니다.",
    sourceLabel: "DRCR 영풍제지 인수자금 분석",
    sourceUrl: "https://www.drcr.co.kr/articles/384",
    graphNodeId: "finance:youngpoong-share-collateral",
  },
  {
    id: "youngpoong-partial-sale",
    date: "2022-11",
    categoryId: "company_funds",
    status: "filing",
    path: "대양금속 → 4개 조합·투자자",
    scale: "307억",
    title: "영풍제지 13.23%를 인수 직후 분산 매각",
    summary: "대양금속은 영풍제지 295만주를 약 307억원에 양도했고, 매수인에게 빌린 단기차입금 일부를 계약금과 상계했습니다.",
    evidence: "KRX 공시에서 주식 수, 양도금액, 계약금 30억6,800만원과 단기차입금 상계 조건을 확인했습니다.",
    sourceLabel: "KRX 영풍제지 지분 양도",
    sourceUrl: "https://kind.krx.co.kr/",
    graphNodeId: "organization:stake-buyers",
  },
  {
    id: "youngpoong-buys-daeyang-cb",
    date: "2022-12",
    categoryId: "company_funds",
    status: "analysis",
    path: "영풍제지 → 대양금속 제23회차 CB",
    scale: "170억",
    title: "피인수회사가 인수회사 전환사채 인수",
    summary: "영풍제지가 대양금속 전환사채 170억원을 인수했고, 분석상 100억원은 대양금속의 채무상환에 쓰였습니다.",
    evidence: "지배권 인수 뒤 피인수회사 자금이 인수회사로 이동한 핵심 회사자금 역류 구간입니다.",
    sourceLabel: "DRCR 영풍제지 인수자금 분석",
    sourceUrl: "https://www.drcr.co.kr/articles/384",
    graphNodeId: "security:daeyang-cb-23",
  },
  {
    id: "youngpoong-market-manipulation",
    date: "2022-10~2023-10",
    categoryId: "market",
    status: "charged",
    path: "총책·3개 팀 → 330개 계좌 → 영풍제지",
    scale: "6,616억",
    title: "13개월간 조직적 시세조종 혐의 기소",
    summary: "검찰은 22만7,448회 주문으로 조정주가를 3,484원에서 4만8,400원까지 약 14배 올리고 약 6,616억원의 부당이득을 얻은 혐의를 공소 제기했습니다.",
    evidence: "2024년 2월 수사결과 기준 16명 기소, 12명 구속기소, 353개 계좌 추징보전입니다. 공소사실은 확정판결과 다릅니다.",
    sourceLabel: "서울남부지검 수사결과",
    sourceUrl: "https://www.spo.go.kr/site/spo/ex/board/View.do?bcIdx=1046002&cbIdx=1403",
    graphNodeId: "case:youngpoong-manipulation",
  },
  {
    id: "youngpoong-owner-charged",
    date: "2024-05",
    categoryId: "market",
    status: "reported",
    path: "영풍제지 실소유주·미등기임원 → 공소",
    scale: "누적 23명",
    title: "기소 범위가 회사 지배층까지 확대",
    summary: "후속 보도에 따르면 검찰은 영풍제지 실소유주와 미등기 임원 2명을 추가 기소해 누적 기소 인원이 23명으로 늘었습니다.",
    evidence: "언론이 검찰 후속 수사를 전한 내용입니다. UI는 실명을 추정하거나 유죄 확정으로 표시하지 않습니다.",
    sourceLabel: "뉴시스 추가 기소 보도",
    sourceUrl: "https://www.newsis.com/view/NISX20240517_0002738890",
    graphNodeId: "role:youngpoong-practical-owner",
  },
  {
    id: "dym-control",
    date: "2025-10",
    categoryId: "control",
    status: "filing",
    path: "공갑상 → 디와이엠파트너스 → 대양금속",
    scale: "14.35%",
    title: "디와이엠파트너스가 차입금으로 대양금속 최대주주 진입",
    summary: "디와이엠파트너스는 대양금속 803만주를 취득해 최대주주가 됐고, 취득자금 방법을 차입금으로 공시했습니다.",
    evidence: "공시 관계인에는 공갑상, 배우자 이옥순, 대양홀딩스컴퍼니가 함께 기재돼 과거와 현재 지배축이 연결됩니다.",
    sourceLabel: "KRX 대양금속 최대주주 변경",
    sourceUrl: "https://kind.krx.co.kr/",
    graphNodeId: "organization:dym-partners",
  },
  {
    id: "crowdworks-control-change",
    date: "2026-02",
    categoryId: "control",
    status: "filing",
    path: "엑스알피1호조합 → 크라우드웍스",
    scale: "12.68%",
    title: "90억원 제3자배정으로 최대주주와 이사회 교체",
    summary: "엑스알피1호조합은 신주 197만3,903주를 취득해 최대주주가 됐고, 김광일 대표 취임과 이사회 재편이 이어졌습니다.",
    evidence: "최대주주 지분율과 납입액은 공시 확인값이며, 6인 이사회 중 5명 교체는 보도 확인값입니다.",
    sourceLabel: "DART 크라우드웍스 최대주주 변경",
    sourceUrl: "https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260206902226",
    graphNodeId: "organization:xrp1",
  },
  {
    id: "daeyang-buys-crowdworks-cb",
    date: "2026-07",
    categoryId: "company_funds",
    status: "filing",
    path: "대양금속 → 크라우드웍스 제2회차 CB",
    scale: "40억",
    title: "대양금속이 크라우드웍스 전환사채 인수",
    summary: "대양금속이 크라우드웍스 제2회차 전환사채 40억원을 인수했고, 전환 시 보유 가능 지분은 10.69%로 공시됐습니다.",
    evidence: "보유 목적은 단순 투자로 기재됐습니다. 전환 가능 지분은 실제 의결권 지분과 구분합니다.",
    sourceLabel: "KRX 대량보유상황보고",
    sourceUrl: "https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260713000711&docno=&method=search&viewerhost=",
    graphNodeId: "security:crowdworks-cb-2",
  },
  {
    id: "crowdworks-buys-daeyang",
    date: "2026-08",
    categoryId: "company_funds",
    status: "filing",
    path: "크라우드웍스 → 디와이엠파트너스 → 대양금속",
    scale: "120억",
    title: "크라우드웍스가 대양금속 4.80% 양수",
    summary: "크라우드웍스는 디와이엠파트너스 보유 대양금속 272만6,100주를 약 120억원에 양수하고 공동경영에 참여하기로 했습니다.",
    evidence: "공동경영 계약은 양측 공동대표 선임과 크라우드웍스 측 이사 4명 지명 구조를 포함합니다. 40억원 CB 거래와 상대방이 다릅니다.",
    sourceLabel: "KRX 타법인 주식 양수결정",
    sourceUrl: "https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260806000432&docno=&method=search&viewerhost=",
    graphNodeId: "event:crowdworks-daeyang-joint-control",
  },
  {
    id: "pangea-reported-funding",
    date: "2026-08",
    categoryId: "company_funds",
    status: "reported",
    path: "대양금속 대여 → 판게아1호조합·박민우 보유주식",
    scale: "41억",
    title: "조합 대여와 전 최대주주 지분 거래의 보도상 연결",
    summary: "보도는 대양금속이 조합에 자금을 대여한 시기와 판게아1호조합이 박민우 보유 크라우드웍스 주식을 약 41억원에 산 거래를 연결했습니다.",
    evidence: "대양금속은 조합 대여와 회수를 인정한 것으로 보도됐지만, 대여금이 해당 주식대금과 동일한 자금인지는 확인되지 않았습니다.",
    sourceLabel: "서울경제TV 자금 연결 보도",
    sourceUrl: "https://www.sentv.co.kr/article/view/sentv202608210130",
    graphNodeId: "organization:pangea1",
  },
];

export const DAEYANG_CROWDWORKS_TEST_CASE: GovernanceTransitionCase = {
  id: "daeyang-crowdworks-2026",
  name: "대양금속-크라우드웍스",
  market: "KOSDAQ",
  stockCode: "A355390",
  referenceDate: "2026-08-31",
  description: "과거 인수금융과 회사자금 이동을 현재 지배권 변화와 같은 구조로 비교합니다.",
  scopeNote: "저장 자료 기준, 크라우드웍스 직접 위법 확인 없음",
  categories: [
    { id: "control", label: "지배권" },
    { id: "acquisition", label: "인수자금" },
    { id: "company_funds", label: "회사자금" },
    { id: "market", label: "시세조종" },
  ],
  comparisonPanels: [
    {
      id: "youngpoong-2022-2024",
      title: "영풍제지 · 2022-2024",
      caption: "과거 실행 구조",
      rows: [
        { label: "지배권", value: "대양금속 → 영풍제지 50.76%" },
        { label: "인수대금", value: "1,300억 · 원래 현금 약 60억" },
        { label: "담보", value: "인수대상 주식 담보 약 761억" },
        { label: "회사자금", value: "영풍제지 → 대양금속 CB 170억" },
        { label: "공소", value: "부당이득 혐의 6,616억 · 330계좌" },
      ],
    },
    {
      id: "crowdworks-2026",
      title: "크라우드웍스 · 2026",
      caption: "현재 연결 구조",
      rows: [
        { label: "대양금속 지배", value: "공갑상 → DYM → 대양금속" },
        { label: "크라우드웍스 지배", value: "엑스알피1호조합 12.68%" },
        { label: "CB", value: "대양금속 → 크라우드웍스 40억" },
        { label: "공동경영", value: "크라우드웍스 → DYM 120억" },
        { label: "취득지분", value: "대양금속 4.80% · 이사 4인 지명" },
      ],
    },
  ],
  events: DAEYANG_CROWDWORKS_EVENTS,
  defaultEventId: "youngpoong-acquisition",
};

export const DAEYANG_CROWDWORKS_GOVERNANCE_GRAPH: GraphData = {
  nodes: [
    { id: "person:lee-oksoon", label: "이옥순", type: "Person", group: "과거 지배", tags: ["대양홀딩스컴퍼니 96%"], properties: { ownership_percent: 96 } },
    { id: "organization:daeyang-holdings", label: "대양홀딩스컴퍼니", type: "Organization", group: "과거 지배", tags: ["대양금속 전 최대주주"], properties: { state: "former_controller" } },
    { id: "company:daeyang-metal", label: "대양금속", type: "Company", group: "연결축", tags: ["KOSPI", "009190"], properties: { stock_code: "009190" }, riskLevel: "high", riskDescription: "영풍제지 인수금융과 현재 크라우드웍스 공동경영을 연결하는 상장사" },
    { id: "company:youngpoong-paper", label: "영풍제지", type: "Company", group: "과거 사례", tags: ["KOSPI", "006740"], properties: { acquired_percent: 50.76 }, riskLevel: "high", riskDescription: "2022년부터 2023년까지 시세조종 공소가 제기된 종목" },
    { id: "history:sfc-takeover", label: "에스에프씨 인수 패턴", type: "RiskSignal", group: "선행 사례", tags: ["공시 분석", "2016"], properties: { acquisition_amount_krw: 7000000000, follow_on_financing_krw: 26500000000 } },
    { id: "finance:youngpoong-acquisition", label: "영풍제지 인수금융", type: "Financing", group: "인수금융", tags: ["원래 현금 60억", "외부조달 1,240억"], properties: { acquisition_amount_krw: 130000000000, analyzed_external_funding_krw: 124000000000 } },
    { id: "finance:youngpoong-share-collateral", label: "영풍제지 주식 담보", type: "Collateral", group: "인수금융", tags: ["761억원", "공시 분석"], properties: { secured_borrowing_krw: 76100000000 } },
    { id: "event:youngpoong-acquisition", label: "영풍제지 지배권 인수", type: "Disclosure", group: "인수금융", tags: ["50.76%", "약 1,300억원"], properties: { date: "2022-11", ownership_percent: 50.76 } },
    { id: "security:daeyang-cb-23", label: "대양금속 제23회차 CB", type: "Security", group: "회사자금", tags: ["170억원", "영풍제지 인수"], properties: { amount_krw: 17000000000 } },
    { id: "organization:stake-buyers", label: "4개 조합·투자자", type: "Organization", group: "회사자금", tags: ["영풍제지 13.23%"], properties: { shares: 2950000, transaction_amount_krw: 30680000000 } },
    { id: "case:youngpoong-manipulation", label: "영풍제지 시세조종 공소", type: "RiskSignal", group: "검찰 공소", tags: ["22만7,448회", "부당이득 혐의 6,616억"], properties: { period: "2022-10~2023-10", alleged_profit_krw: 661600000000 }, riskLevel: "high", riskDescription: "공소사실이며 확정판결과 구분해야 함" },
    { id: "organization:manipulation-teams", label: "총책·3개 시세조종팀", type: "Organization", group: "검찰 공소", tags: ["검찰 공소"], properties: { teams: 3 } },
    { id: "organization:manipulation-accounts", label: "모집계좌 330개", type: "AccountGroup", group: "검찰 공소", tags: ["353개 계좌 추징보전"], properties: { used_accounts: 330, preserved_accounts: 353 } },
    { id: "role:youngpoong-practical-owner", label: "영풍제지 실소유주 역할", type: "PersonRole", group: "검찰 공소", tags: ["2024년 5월 추가 기소 보도"], properties: { legal_state: "charged_reported" } },
    { id: "person:gong-gapsang", label: "공갑상", type: "Person", group: "현재 지배", tags: ["디와이엠파트너스 최대주주"], properties: { related_party: "이옥순 배우자" } },
    { id: "organization:dym-partners", label: "디와이엠파트너스", type: "Organization", group: "현재 지배", tags: ["대양금속 최대주주", "차입금 취득"], properties: { ownership_percent_at_entry: 14.35 } },
    { id: "company:crowdworks", label: "크라우드웍스", type: "Company", group: "현재 연결", tags: ["KOSDAQ", "A355390"], properties: { stock_code: "355390" }, riskLevel: "medium", riskDescription: "대양금속과 CB 투자 및 공동경영 관계. 직접 위법 사실은 현재 자료에서 확인되지 않음" },
    { id: "organization:xrp1", label: "엑스알피1호조합", type: "Organization", group: "현재 연결", tags: ["크라우드웍스 최대주주", "12.68%"], properties: { ownership_percent: 12.68, paid_in_capital_krw: 9000997680 } },
    { id: "security:crowdworks-cb-2", label: "크라우드웍스 제2회차 CB", type: "Security", group: "현재 연결", tags: ["40억원", "전환 가능 10.69%"], properties: { amount_krw: 4000000000, convertible_percent: 10.69 } },
    { id: "event:crowdworks-daeyang-joint-control", label: "대양금속 지분 양수·공동경영", type: "Disclosure", group: "현재 연결", tags: ["4.80%", "약 120억원"], properties: { date: "2026-08-06", shares: 2726100, amount_krw: 11997566100 } },
    { id: "organization:pangea1", label: "판게아1호조합", type: "Organization", group: "보도 연결", tags: ["보도", "동일 자금 미확인"], properties: { reported_share_purchase_krw: 4100000000 } },
    { id: "person:park-minwoo", label: "박민우", type: "Person", group: "보도 연결", tags: ["크라우드웍스 전 최대주주"], properties: { state: "former_controller" } },
  ],
  edges: [
    { id: "edge:lee-controls-holdings", source: "person:lee-oksoon", target: "organization:daeyang-holdings", relation: "CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 96, directed: true, properties: { ownership_percent: 96 } },
    { id: "edge:holdings-former-daeyang", source: "organization:daeyang-holdings", target: "company:daeyang-metal", relation: "FORMER_CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 1, directed: true, is_active: false, properties: {} },
    { id: "edge:sfc-precedes", source: "history:sfc-takeover", target: "company:daeyang-metal", relation: "PRECEDES_CONTROL_PATTERN_OF", category: "history", weight: 1, directed: true, properties: { evidence_state: "analysis" } },
    { id: "edge:finance-funds-daeyang", source: "finance:youngpoong-acquisition", target: "company:daeyang-metal", relation: "FINANCED_ACQUISITION_BY", category: "capital", weight: 124, directed: true, properties: { analyzed_external_funding_krw: 124000000000 } },
    { id: "edge:daeyang-acquires", source: "company:daeyang-metal", target: "event:youngpoong-acquisition", relation: "ACQUIRED_CONTROL_THROUGH", category: "ownership", weight: 130, directed: true, properties: { amount_krw: 130000000000 } },
    { id: "edge:acquisition-targets-youngpoong", source: "event:youngpoong-acquisition", target: "company:youngpoong-paper", relation: "ACQUIRED_CONTROL_OF", category: "ownership", weight: 50.76, directed: true, properties: { ownership_percent: 50.76 } },
    { id: "edge:youngpoong-collateral", source: "company:youngpoong-paper", target: "finance:youngpoong-share-collateral", relation: "SHARES_PLEDGED_AS", category: "collateral", weight: 76.1, directed: true, properties: { secured_borrowing_krw: 76100000000 } },
    { id: "edge:youngpoong-buys-cb", source: "company:youngpoong-paper", target: "security:daeyang-cb-23", relation: "ACQUIRED", category: "capital", weight: 17, directed: true, properties: { amount_krw: 17000000000 } },
    { id: "edge:daeyang-issues-cb23", source: "security:daeyang-cb-23", target: "company:daeyang-metal", relation: "ISSUED_BY", category: "capital", weight: 17, directed: true, properties: {} },
    { id: "edge:daeyang-sells-stake", source: "company:daeyang-metal", target: "organization:stake-buyers", relation: "TRANSFERRED_YOUNGPOONG_STAKE_TO", category: "capital", weight: 30.68, directed: true, properties: { shares: 2950000, amount_krw: 30680000000 } },
    { id: "edge:teams-use-accounts", source: "organization:manipulation-teams", target: "organization:manipulation-accounts", relation: "USED", category: "case", weight: 330, directed: true, properties: { accounts: 330 } },
    { id: "edge:accounts-orders", source: "organization:manipulation-accounts", target: "case:youngpoong-manipulation", relation: "SUBMITTED_MANIPULATIVE_ORDERS_FOR", category: "case", weight: 227.448, directed: true, properties: { orders: 227448 } },
    { id: "edge:case-targets-youngpoong", source: "case:youngpoong-manipulation", target: "company:youngpoong-paper", relation: "TARGETED", category: "case", weight: 1, directed: true, properties: { legal_state: "charged" } },
    { id: "edge:owner-charged", source: "role:youngpoong-practical-owner", target: "case:youngpoong-manipulation", relation: "CHARGED_IN", category: "case", weight: 1, directed: true, properties: { evidence_state: "reported" } },
    { id: "edge:gong-controls-dym", source: "person:gong-gapsang", target: "organization:dym-partners", relation: "CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 1, directed: true, is_active: true, properties: {} },
    { id: "edge:dym-controls-daeyang", source: "organization:dym-partners", target: "company:daeyang-metal", relation: "CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 14.35, directed: true, is_active: true, start_date: "2025-10-01", properties: { acquisition_funds: "borrowed" } },
    { id: "edge:xrp-controls-crowdworks", source: "organization:xrp1", target: "company:crowdworks", relation: "CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 12.68, directed: true, is_active: true, start_date: "2026-02-06", properties: { ownership_percent: 12.68 } },
    { id: "edge:daeyang-buys-cw-cb", source: "company:daeyang-metal", target: "security:crowdworks-cb-2", relation: "ACQUIRED", category: "capital", weight: 4, directed: true, start_date: "2026-07-13", properties: { amount_krw: 4000000000 } },
    { id: "edge:cw-issues-cb", source: "security:crowdworks-cb-2", target: "company:crowdworks", relation: "ISSUED_BY", category: "capital", weight: 4, directed: true, properties: {} },
    { id: "edge:crowdworks-buys-daeyang", source: "company:crowdworks", target: "event:crowdworks-daeyang-joint-control", relation: "TRANSFEREE_OF", category: "capital", weight: 12, directed: true, start_date: "2026-08-06", properties: { amount_krw: 11997566100 } },
    { id: "edge:dym-transfers-daeyang", source: "organization:dym-partners", target: "event:crowdworks-daeyang-joint-control", relation: "TRANSFEROR_OF", category: "capital", weight: 12, directed: true, start_date: "2026-08-06", properties: {} },
    { id: "edge:joint-control-target", source: "event:crowdworks-daeyang-joint-control", target: "company:daeyang-metal", relation: "JOINT_CONTROL_OF", category: "governance", weight: 4.8, directed: true, start_date: "2026-08-06", properties: { ownership_percent: 4.8 } },
    { id: "edge:daeyang-reported-loan", source: "company:daeyang-metal", target: "organization:pangea1", relation: "REPORTED_LOAN_TO", category: "reported", weight: 1, directed: true, properties: { exact_fund_match_confirmed: false } },
    { id: "edge:pangea-buys-park-shares", source: "organization:pangea1", target: "person:park-minwoo", relation: "ACQUIRED_CROWDWORKS_SHARES_FROM", category: "reported", weight: 4.1, directed: true, properties: { reported_amount_krw: 4100000000 } },
    { id: "edge:park-former-crowdworks", source: "person:park-minwoo", target: "company:crowdworks", relation: "FORMER_CONTROLLING_SHAREHOLDER_OF", category: "ownership", weight: 1, directed: true, is_active: false, properties: {} },
  ],
};
