import type { GraphStyleConfig } from '../types/graph'

export const STYLE_PRESETS: Record<string, GraphStyleConfig> = {
  'AI Studio': {
    presetName: 'AI Studio',
    backgroundColor: '#090d12',
    nodeColor: '#7dd3fc',
    nodeSize: 5.8,
    nodeOpacity: 0.94,
    nodeBorderColor: '#dbeafe',
    nodeBorderWidth: 0.8,
    edgeColor: '#728196',
    edgeWidth: 1.05,
    edgeOpacity: 0.62,
    arrowVisibility: true,
    labelVisible: true,
    labelFontSize: 11,
    maxLabelLength: 26,
    labelVisibilityZoom: 1.15,
    hoverColor: '#34d399',
    selectedColor: '#f59e0b',
    highlightedColor: '#a3e635',
    nodeTypeStyles: {
      Person: { color: '#7dd3fc', size: 6.2, shape: 'circle', borderColor: '#dbeafe', borderWidth: 0.9 },
      Project: { color: '#34d399', size: 7, shape: 'diamond', borderColor: '#bbf7d0', borderWidth: 1 },
      Organization: { color: '#f6b34b', size: 7.4, shape: 'square', borderColor: '#fde68a', borderWidth: 1 },
      System: { color: '#a78bfa', size: 6.4, shape: 'triangle', borderColor: '#ddd6fe', borderWidth: 1 },
      Metric: { color: '#fb7185', size: 5.8, shape: 'circle', borderColor: '#fecdd3', borderWidth: 0.9 },
    },
    styleRules: [],
  },
  Default: {
    presetName: 'Default',
    backgroundColor: '#ffffff',
    nodeColor: '#4f46e5',
    nodeSize: 5,
    nodeOpacity: 0.9,
    nodeBorderColor: '#1f2937',
    nodeBorderWidth: 1,
    edgeColor: '#6b7280',
    edgeWidth: 1.2,
    edgeOpacity: 0.7,
    arrowVisibility: true,
    labelVisible: true,
    labelFontSize: 11,
    maxLabelLength: 24,
    labelVisibilityZoom: 1.3,
    hoverColor: '#0ea5e9',
    selectedColor: '#f97316',
    highlightedColor: '#22c55e',
    nodeTypeStyles: {},
    styleRules: [],
  },
  'Dark mode': {
    presetName: 'Dark mode',
    backgroundColor: '#0b1020',
    nodeColor: '#7c83fd',
    nodeSize: 5,
    nodeOpacity: 0.92,
    nodeBorderColor: '#f8fafc',
    nodeBorderWidth: 1,
    edgeColor: '#94a3b8',
    edgeWidth: 1.15,
    edgeOpacity: 0.6,
    arrowVisibility: true,
    labelVisible: true,
    labelFontSize: 11,
    maxLabelLength: 24,
    labelVisibilityZoom: 1.2,
    hoverColor: '#22d3ee',
    selectedColor: '#fb7185',
    highlightedColor: '#4ade80',
    nodeTypeStyles: {},
    styleRules: [],
  },
  'High contrast': {
    presetName: 'High contrast',
    backgroundColor: '#000000',
    nodeColor: '#ffffff',
    nodeSize: 6,
    nodeOpacity: 1,
    nodeBorderColor: '#000000',
    nodeBorderWidth: 2,
    edgeColor: '#facc15',
    edgeWidth: 1.6,
    edgeOpacity: 1,
    arrowVisibility: true,
    labelVisible: true,
    labelFontSize: 12,
    maxLabelLength: 24,
    labelVisibilityZoom: 1,
    hoverColor: '#00e5ff',
    selectedColor: '#ff006e',
    highlightedColor: '#00ff85',
    nodeTypeStyles: {},
    styleRules: [],
  },
  'Obsidian-like': {
    presetName: 'Obsidian-like',
    backgroundColor: '#181a1f',
    nodeColor: '#7aa2f7',
    nodeSize: 5,
    nodeOpacity: 0.95,
    nodeBorderColor: '#cdd6f4',
    nodeBorderWidth: 1,
    edgeColor: '#6c7086',
    edgeWidth: 1.2,
    edgeOpacity: 0.75,
    arrowVisibility: true,
    labelVisible: true,
    labelFontSize: 11,
    maxLabelLength: 22,
    labelVisibilityZoom: 1.2,
    hoverColor: '#89dceb',
    selectedColor: '#f9e2af',
    highlightedColor: '#a6e3a1',
    nodeTypeStyles: {},
    styleRules: [],
  },
}

export const DEFAULT_STYLE = { ...STYLE_PRESETS.Default }
